Repository CECTC/dbpack, pull requests merged in 2022-07, with the labels that each got.

#195 fix: in tcc mode, json.Unmarshal requestContext.Headers failed
  pkg/dt/context.go
  pkg/dt/context_test.go
  pkg/dt/distributed_transaction_manger.go
  pkg/filter/dt/filter_http.go
  pkg/filter/dt/transaction.go
  pkg/listener/http.go
Labels: bug

#200 refactor: support manipulating the same data in different transaction…
  pkg/dt/distributed_transaction_manger.go
  pkg/dt/storage/etcd/etcd.go
  pkg/dt/storage/storagedriver.go
  pkg/filter/dt/exec/executor.go
  pkg/filter/dt/exec/prepare_global_lock.go
  pkg/filter/dt/exec/prepare_global_lock_test.go
  pkg/filter/dt/exec/prepare_select_for_update.go
  pkg/filter/dt/exec/prepare_select_for_update_test.go
  pkg/filter/dt/exec/query_global_lock.go
  pkg/filter/dt/exec/query_global_lock_test.go
  pkg/filter/dt/exec/query_select_for_update.go
  pkg/filter/dt/exec/query_select_for_update_test.go
  pkg/filter/dt/filter_mysql.go
  pkg/filter/dt/filter_mysql_prepare.go
  pkg/filter/dt/filter_mysql_query.go
  test/sdb/distributed_transaction_test.go
Labels: enhancement

#183 feat: support count aggregate func on sharded table
  pkg/listener/mysql.go
  pkg/mysql/conn.go
  pkg/mysql/rows.go
  pkg/optimize/optimizer.go
  pkg/packet/mysql.go
  pkg/plan/query.go
  pkg/plan/query_test.go
  pkg/plan/result.go
  pkg/plan/result_test.go
  pkg/visitor/param.go
  test/shd/sharding_test.go
Labels: enhancement, sharding

#177 feat: add more trace span and integrate with jaeger
  cmd/cmd.go
  go.mod
  go.sum
  pkg/config/config.go
  pkg/dt/mysql_undo_log_manager.go
  pkg/executor/read_write_splitting.go
  pkg/executor/sharding.go
  pkg/executor/single_db.go
  pkg/filter/dt/exec/prepare_delete.go
  pkg/filter/dt/exec/prepare_insert.go
  pkg/filter/dt/exec/prepare_select_for_update.go
  pkg/filter/dt/exec/prepare_update.go
  pkg/filter/dt/exec/query_delete.go
  pkg/filter/dt/exec/query_insert.go
  pkg/filter/dt/exec/query_select_for_update.go
  pkg/filter/dt/exec/query_update.go
  pkg/filter/dt/filter_http.go
  pkg/filter/dt/filter_mysql.go
  pkg/filter/dt/filter_mysql_prepare.go
  pkg/filter/dt/filter_mysql_query.go
  pkg/filter/dt/transaction.go
  pkg/listener/http.go
  pkg/listener/mysql.go
  pkg/proto/interface.go
  pkg/sql/db.go
  pkg/tracing/constant.go
  pkg/tracing/tracer.go
  testdata/mock_db.go
  testdata/mock_db_manager.go
  testdata/mock_tx.go
Labels: WIP

#193 feature: support cross-database update transactions
  pkg/plan/delete.go
  pkg/plan/update.go
  test/shd/sharding_test.go
Labels: enhancement, sharding

#212 feature: support gin middleware and grpc interceptor
  cmd/cmd.go
  go.mod
  go.sum
  pkg/contrib/gin/global_transaction.go
  pkg/contrib/grpc/global_transaction.go
  pkg/dt/distributed_transaction_manger.go
  pkg/dt/storage/etcd/etcd.go
  test/sdb/distributed_transaction_test.go
Labels: enhancement

#214 fix: in sharding mode, merge result miss some rows
  makefile
  pkg/executor/sharding.go
  pkg/plan/result.go
Labels: bug
